include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    - prefer_single_quotes
    - prefer_relative_imports
    - prefer_final_fields
    - prefer_const_constructors

analyzer:
  plugins:
    - custom_lint
