name: nice
description: 'A new Flutter project.'

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  odu_core:
    git:
      url: https://github.com/pretodev/odu_core.git
      ref: main

  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  pocketbase: ^0.23.2
  material_symbols_icons: ^4.2892.0
  dio: ^5.9.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.12.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^10.0.0
  auto_injector: ^2.1.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
