// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// PLACEHOLDER FILE.
// Substitua executando `flutterfire configure` na raiz do projeto.
// Sem a regeneração, Firebase.initializeApp lançará um erro em tempo de execução.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions ainda não foi configurado para web. '
        'Rode `flutterfire configure` para regerar este arquivo.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions ainda não foi gerado. '
          'Rode `flutterfire configure` na raiz do projeto.',
        );
    }
  }
}
