// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzfZSv86M_-2af5vr10DUSik3GiNSn4W8',
    appId: '1:398445316766:android:8cfad468126a091084898f',
    messagingSenderId: '398445316766',
    projectId: 'valney-fitness',
    databaseURL: 'https://valney-fitness.firebaseio.com',
    storageBucket: 'valney-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GPRpQtkYecCHxgWeek4-O-PYvmHTGls',
    appId: '1:398445316766:ios:b5d65a13106f088384898f',
    messagingSenderId: '398445316766',
    projectId: 'valney-fitness',
    databaseURL: 'https://valney-fitness.firebaseio.com',
    storageBucket: 'valney-fitness.firebasestorage.app',
    androidClientId: '398445316766-nqdu3gv2rvl56j4g5v497oi4o5mus53n.apps.googleusercontent.com',
    iosBundleId: 'br.com.odulab.nice',
  );

}